
GET http://localhost:3003/api/blogs

###

GET http://localhost:3003/api/blogs/11

###

POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RCbG9nIiwiaWQiOiI2NTZlMzEyNDQ5YzYyMWM1MTg5Yjk0MzAiLCJpYXQiOjE3MDE3MjEzMzZ9.A_BdrYj0FP3VOUKsGXR86bI6jHPGGVN1S9-6hbdlIwg

{
    "title": "2525253 test",
    "author": "some dude",
    "url": "some url",
    "likes": 140
}

###

POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json

{
    "title": "blog my 123"
}

###
POST  http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "blog main 2",
    "name": "logblog ",
    "password": "aspasdasd123aspwasf"
}

###
POST  http://localhost:3003/api/users
Content-Type: application/json

{ 
    "username": "testBlog",
    "name": "blog main 2",
    "password": "1234"
}

###

GET http://localhost:3003/api/users


###

POST http://localhost:3003/api/login
Content-Type:  application/json

{
    "username": "testBlog",
    "password": "1234"  
}