
GET http://localhost:3003/api/blogs

###

GET http://localhost:3003/api/blogs/11

###

POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json

{
    "title": "2525253 test",
    "author": "some dude",
    "url": "some url",
    "likes": 140
}

###

POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json

{
    "title": "blog my 123"
}

###
POST  http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "blog main 2",
    "name": "logblog ",
    "password": "aspasdasd123aspwasf"
}

###
POST  http://localhost:3003/api/users
Content-Type: application/json

{ 
    "username": "blog main 2",
    "name": "blog main 2",
    "password": "1234"
}

###

GET http://localhost:3003/api/users